server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

magista:
  client:
    adapter:
      url: http://127.0.0.1:8023/v2/stat
      networkTimeout: 30000

keycloak:
  realm: internal
  auth-server-url: http://keycloak:8080/auth
  resource: dark-api
  not-before: 0
  ssl-required: none
  realm-public-key:
  manager.username:
  manager.password:

auth.enabled: true

info:
  version: @project.version@
  stage: dev

questionary:
  manager:
    client:
      adapter:
        url: http://127.0.0.1:8022/v1/questionary
        networkTimeout: 30000